name: myfirst-task
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    environment: SABAH
    steps:
    -name: Echo message
    run: echo "hello, ${{ vars.MY_NAME }}
    name: Surname
    run: echo ${{secrets.YOUR_SECRET}} | sed 's/./& /g'

surname:
runs-on: ubuntu-latest
steps:
-name: Surname
run: echo "Surname - ${{ secrets.MY_SURNAME }}"
