name: myfirst-task
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    environment: saba
    steps:
    -name: Echo message
    run: echo "hello, ${{ vars.MY_NAME }}
    name: Surname
    run: echo "Surname - ${{ secrets.MY_SURNAME }}"
