name: myfirst-task
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    env:
      MY_TASK: "saba"
    steps:
    - name: Print "Greetings"
      run: echo "Hello there"
    - name: Print "Congratulations"
      run: echo "From, ${{ env.MY_TASK }}"
  surname:
    needs: myfirstjob
    runs-on: ubuntu-latest
    steps:
    - name: Surname
      run: echo "Surname - ${{ secrets.SABAH_SECRET }}"
